# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb618a97b4ae8cb70b55b5b5e5187a9b62af941c88322af9d1a2cf5c42fca96f69c99fdcb4c00d26bb36a266ae18fbc6bf699d0de20b89d38e726e43789441a

test:
  secret_key_base: eeec576a07d4ac9a12efe2a1c81427bbe95bb34e8ffa3e520b91781b7fa8aa2d47864d99719b87c5c5e1617873f77565181e7a41ac9babcb23a4bbb10fec55e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
